on: push
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo
        echo From secret: "${{ secrets.ACTION_TEST_SECRET }}"
        echo From envvar: "$MY_VAR"
      env:
        MY_VAR: ${{ secrets.ACTION_TEST_SECRET }}

